[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = ["dotnet restore TaskManager/TaskManager.csproj"]

[phases.build]
cmds = ["dotnet publish TaskManager/TaskManager.csproj -c Release -o out"]

[phases.start]
cmd = "./out/TaskManager"
